services:
  tor:
    container_name: btcstack_tor
    user: "${UID}:${GID}"
    build:
      context: ./dockerfiles/
      dockerfile: Dockerfile.tor
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./data/tor:/var/lib/tor/
      - ./configs/torrc:/etc/tor/torrc:ro
    restart: unless-stopped

  bitcoin:
    container_name: btcstack_bitcoin
    user: "${UID}:${GID}"
    depends_on: [tor]
    build:
      context: ./dockerfiles/
      dockerfile: Dockerfile.bitcoin
      args:
        BITCOIN_ARCH: ${BITCOIN_ARCH}
        BITCOIN_CORE_VERSION: ${BITCOIN_CORE_VERSION}
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./data/bitcoin:/data/.bitcoin
      - ./data/tor:/data/cookie:ro
      - ./configs/bitcoin.conf:/data/.bitcoin/bitcoin.conf:ro
    restart: unless-stopped

  electrs:
    container_name: btcstack_electrs
    user: "${UID}:${GID}"
    depends_on: [bitcoin]
    build:
      context: ./dockerfiles/
      dockerfile: Dockerfile.electrs
      args:
        ELECTRS_VERSION: ${ELECTRS_VERSION}
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./configs/electrs.toml:/data/electrs.toml:ro
      - ./data/electrs:/data
      - ./data/bitcoin:/data/.bitcoin:ro
    restart: unless-stopped

  lnd:
    container_name: btcstack_lnd
    user: "${UID}:${GID}"
    depends_on: [bitcoin]
    build:
      context: ./dockerfiles/
      dockerfile: Dockerfile.lnd
      args:
        LND_ARCH: ${LND_ARCH}
        LND_VERSION: ${LND_VERSION}
        UID: ${UID}
        GID: ${GID}
    ports:
      - "8080:8080"
    volumes:
      - ./data/lnd:/data/.lnd
      - ./data/tor:/var/lib/tor:ro
      - ./data/bitcoin:/data/.bitcoin:ro
      - ./configs/lnd.conf:/data/.lnd/lnd.conf:ro
    environment:
      LND_PASSWORD: ${LND_PASSWORD}
    restart: unless-stopped

  scb:
    container_name: btcstack_scb
    user: "${UID}:${GID}"
    depends_on: [lnd]
    build:
      context: ./dockerfiles/
      dockerfile: Dockerfile.scb
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./data/scb:/data
      - ./data/lnd:/lnd:ro
    environment:
      SCB_REPO: ${SCB_REPO}
    restart: unless-stopped

  rtl:
    container_name: btcstack_rtl
    user: "${UID}:${GID}"
    depends_on: [lnd]
    build:
      context: ./dockerfiles/
      dockerfile: Dockerfile.rtl
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./configs/rtl.json:/data/RTL/RTL-Config.json
      - ./configs/lnd.conf:/data/lnd.conf:ro
      - ./data/lnd:/data/.lnd:ro
      - ./data/rtl:/data/rtldb
    environment:
      APP_PASSWORD: ${RTL_PASSWORD}
    restart: unless-stopped

